function Hd = LowPass_50Hz
%LOWPASS_50HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 12-Jan-2022 11:20:11

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

Fstop1 = 1.7;             % First Stopband Frequency
Fpass1 = 2;               % First Passband Frequency
Fpass2 = 4;               % Second Passband Frequency
Fstop2 = 4.3;             % Second Stopband Frequency
Dstop1 = 1.77827941e-05;  % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
