function GammaDeltaSpindle(X1, Y1, X2, Y2, X3, Y3, X4, X5, X6)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, X5, X6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  X5:  vector of x data
%  X6:  vector of x data

%  Auto-generated by MATLAB on 19-Jul-2021 17:58:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.583837209302326 0.775 0.341162790697675]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'DisplayName','Wake','MarkerSize',5,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'Parent',axes1,'DisplayName','NREM','MarkerSize',5,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 1 0]);

% Create plot
plot(X3,Y3,'Parent',axes1,'DisplayName','REM','MarkerSize',5,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 1 1]);

% Create xlabel
xlabel('Delta_power');

% Create ylabel
ylabel('Gamma_power');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.00216574511881481 0.0367888516509196]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1.92832562003072e-06 0.00072875875163166]);
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

% Create subplot
subplot1 = subplot(2,1,2,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X4,Y1,'Parent',subplot1,'DisplayName','Wake','MarkerSize',5,...
    'Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X5,Y2,'Parent',subplot1,'DisplayName','NREM','MarkerSize',5,...
    'Marker','.',...
    'LineStyle','none',...
    'Color',[0 1 0]);

% Create plot
plot(X6,Y3,'Parent',subplot1,'DisplayName','REM','MarkerSize',5,...
    'Marker','.',...
    'LineStyle','none',...
    'Color',[0 1 1]);

% Create xlabel
xlabel('Spindle_power');

% Create ylabel
ylabel('Gamma_power');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[2.33904096190567e-05 0.00518359170532964]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-3.12658171992017e-06 0.000779892286204608]);
box(subplot1,'on');
% Create legend
legend2 = legend(subplot1,'show');
set(legend2,'Location','best');

